# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7a0c57c9519c1928cfb22f0c6850271424e81dae54dc2e8489d9fbcc062943e64a365e6fe35803175d09bcb5bbe36a8beb0f01e0ef1d682facc5d5e2c69c070

test:
  secret_key_base: f0f0cab3f2b6b2eeaa412dde5737a647c701e7b96a14b1ab8fe2d7ce2aee7c9b111dd75b5f7b07fc5f18ae770a75c4da4ea9868b2da5ecd7d9fade6d14f50e0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
